name: Build and Commit Dist

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js (ou sua stack)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Build do projeto
      - name: Build project
        run: npm run build
      
      # Commit e push para uma branch separada
      - name: Commit and push to a new branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b update-dist
          git add dist
          git commit -m "Update dist folder [skip ci]" || echo "No changes to commit"
          git push origin update-dist

      # Criar pull request automaticamente
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-dist
          title: "Update dist folder"
          body: "This pull request updates the dist folder."
